---
# tasks file for hosts

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'FreeBSD'

- include: hostname.yml
  when: enable_hostname_file_update == true

- include: hosts.yml
  when: enable_hosts_file_update == true
